# Generated by Django 4.0.5 on 2022-07-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistEquipamentoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'core_checklist_equipamento_seguranca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descrição do CheckList')),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoSeguraca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_equipamento_seguranca', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descrição do Equipamento de Segurança')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_veiculo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descrição do Veículo')),
            ],
        ),
        migrations.CreateModel(
            name='VeiculoEquipamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipamento_seguranca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipamentoseguraca')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.veiculos')),
            ],
        ),
        migrations.CreateModel(
            name='CheckListDetalhe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkbox', models.IntegerField(blank=True, null=True, verbose_name='Checkbox')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.checklist')),
                ('veiculo_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculoequipamento')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='equipamento_seguranca',
            field=models.ManyToManyField(to='core.equipamentoseguraca'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.authuser'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='veiculos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculos'),
        ),
    ]
