# Generated by Django 4.0.5 on 2022-07-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_checklist_equipamentoseguraca_veiculos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistEquipamentoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'core_checklist_equipamento_seguranca',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='checklist',
            name='descricao',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Descrição do CheckList'),
        ),
    ]
